namespace Operativ.BE.Enums;
public enum TipoError
{
    ErrorUsuarioNoExiste,
    ErrorContrasenaIncorrecta,
    ErrorUsuarioBloqueado,
    ErrorConexionBaseDatos,
    ErrorSesionExpirada,
    ErrorEnvioEmail,
    ErrorUsuarioYaExiste,
    ErrorEmailYaRegistrado,
    ErrorContrasenaActualIncorrecta,
    ErrorClaveNoCumpleComplejidad,
    ErrorIntegridadCorrupta,
    ErrorCredencialesEmergenciaInvalidas,
    ErrorArchivoEmergenciaNoDisponible,
    ErrorUltimoUsuarioDeFamilia,
    ErrorPatenteYaAsignada,
    ErrorPatenteNoAsignada,
    ErrorSinPermiso,
    ErrorOperacionBackupFallida,
    ErrorArchivoBackupNoExiste,
    ErrorPaqueteNoExiste,
    ErrorPaqueteYaExiste,
    ErrorPaqueteSinProgramas,
    ErrorActivoNoExiste,
    ErrorActivoYaExiste,
    FalloNoManejadoGenerico
}
