<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Operativ.DAL</RootNamespace>
    <AssemblyName>Operativ.DAL</AssemblyName>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Data" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Operativ.BE\Operativ.BE.csproj" />
    <ProjectReference Include="..\Operativ.Comun\Operativ.Comun.csproj" />
  </ItemGroup>

</Project>
